module.exports = [
  {name: "Abel", game: "SF4"},
  {name: "Akuma", game: "SF4"},
  {name: "Balrog", game: "SF4"},
  {name: "Blanka", game: "SF4"},
  {name: "C. Viper", game: "SF4"},
  {name: "Cammy", game: "SF4"},
  {name: "Chun-Li", game: "SF4"},
  {name: "Dan", game: "SF4"},
  {name: "Dhalsim", game: "SF4"},
  {name: "E. Honda", game: "SF4"},
  {name: "El Fuerte", game: "SF4"},
  {name: "Fei Long", game: "SF4"},
  {name: "Gen", game: "SF4"},
  {name: "Gouken", game: "SF4"},
  {name: "Guile", game: "SF4"},
  {name: "Ken", game: "SF4"},
  {name: "M. Bison", game: "SF4"},
  {name: "Rose", game: "SF4"},
  {name: "Rufus", game: "SF4"},
  {name: "Ryu", game: "SF4"},
  {name: "Sagat", game: "SF4"},
  {name: "Sakura", game: "SF4"},
  {name: "Seth", game: "SF4"},
  {name: "Vega", game: "SF4"},
  {name: "Zangief", game: "SF4"},
  {name: "Adon", game: "SF4"},
  {name: "Cody", game: "SF4"},
  {name: "Dee Jay", game: "SF4"},
  {name: "Dudley", game: "SF4"},
  {name: "Guy", game: "SF4"},
  {name: "Hakan", game: "SF4"},
  {name: "Ibuki", game: "SF4"},
  {name: "Juri", game: "SF4"},
  {name: "Makoto", game: "SF4"},
  {name: "T. Hawk", game: "SF4"},
  {name: "Evil Ryu", game: "SF4"},
  {name: "Oni", game: "SF4"},
  {name: "Yang", game: "SF4"},
  {name: "Yun", game: "SF4"}  
]
