module.exports = [
  {name: "Abel", game: "SF4AE"},
  {name: "Akuma", game: "SF4AE"},
  {name: "Balrog", game: "SF4AE"},
  {name: "Blanka", game: "SF4AE"},
  {name: "C. Viper", game: "SF4AE"},
  {name: "Cammy", game: "SF4AE"},
  {name: "Chun-Li", game: "SF4AE"},
  {name: "Dan", game: "SF4AE"},
  {name: "Dhalsim", game: "SF4AE"},
  {name: "E. Honda", game: "SF4AE"},
  {name: "El Fuerte", game: "SF4AE"},
  {name: "Fei Long", game: "SF4AE"},
  {name: "Gen", game: "SF4AE"},
  {name: "Gouken", game: "SF4AE"},
  {name: "Guile", game: "SF4AE"},
  {name: "Ken", game: "SF4AE"},
  {name: "M. Bison", game: "SF4AE"},
  {name: "Rose", game: "SF4AE"},
  {name: "Rufus", game: "SF4AE"},
  {name: "Ryu", game: "SF4AE"},
  {name: "Sagat", game: "SF4AE"},
  {name: "Sakura", game: "SF4AE"},
  {name: "Seth", game: "SF4AE"},
  {name: "Vega", game: "SF4AE"},
  {name: "Zangief", game: "SF4AE"},
  {name: "Adon", game: "SF4AE"},
  {name: "Cody", game: "SF4AE"},
  {name: "Dee Jay", game: "SF4AE"},
  {name: "Dudley", game: "SF4AE"},
  {name: "Guy", game: "SF4AE"},
  {name: "Hakan", game: "SF4AE"},
  {name: "Ibuki", game: "SF4AE"},
  {name: "Juri", game: "SF4AE"},
  {name: "Makoto", game: "SF4AE"},
  {name: "T. Hawk", game: "SF4AE"},
  {name: "Evil Ryu", game: "SF4AE"},
  {name: "Oni", game: "SF4AE"},
  {name: "Yang", game: "SF4AE"},
  {name: "Falco", game: "SSBM"},  
  {name: "Fox", game: "SSBM"},  
  {name: "Shiek", game: "SSBM"},  
  {name: "Zelda", game: "SSBM"},  
  {name: "Marth", game: "SSBM"},  
  {name: "Jigglypuff", game: "SSBM"},  
]
